name: cpu_release

on:
  push:
    tags:
      - "v*.*.*"

env:
  libtorch_version: 2.0.1

jobs:
  release_linux_glibc232:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: make
        working-directory: ./lib
        run: |
          wget -q -O libtorch.zip https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-${{ env.libtorch_version }}%2Bcpu.zip
          unzip -qq libtorch.zip
          cmake -DCMAKE_PREFIX_PATH=./libtorch -DCMAKE_BUILD_TYPE=Release .
          make
          mv libgotorch.so libgotorch_cpu.glibc232.so

      - name: upload
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./lib/libgotorch_cpu.glibc232.so
          allowUpdates: true
          generateReleaseNotes: true
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          omitBody: true

  release_linux_glibc231:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: make
        working-directory: ./lib
        run: |
          wget -q -O libtorch.zip https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-${{ env.libtorch_version }}%2Bcpu.zip
          unzip -qq libtorch.zip
          cmake -DCMAKE_PREFIX_PATH=./libtorch -DCMAKE_BUILD_TYPE=Release .
          make
          mv libgotorch.so libgotorch_cpu.glibc231.so

      - name: upload
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./lib/libgotorch_cpu.glibc231.so
          allowUpdates: true
          generateReleaseNotes: true
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          omitBody: true

  release_macos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3

      - name: make
        working-directory: ./lib
        run: |
          wget -q -O libtorch.zip https://download.pytorch.org/libtorch/cpu/libtorch-macos-${{ env.libtorch_version }}.zip
          unzip -qq libtorch.zip
          cmake -DCMAKE_PREFIX_PATH=./libtorch -DCMAKE_BUILD_TYPE=Release .
          make
          mv libgotorch.dylib libgotorch_cpu.dylib

      - name: upload
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./lib/libgotorch_cpu.dylib
          allowUpdates: true
          generateReleaseNotes: true
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          omitBody: true

  release_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1.3.1

      - name: make
        working-directory: ./lib
        run: |
          curl -o libtorch.zip https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-${{ env.libtorch_version }}%2Bcpu.zip
          unzip -qq libtorch.zip
          cmake -DCMAKE_PREFIX_PATH=${{ github.workspace }}\lib\libtorch .
          msbuild gotorch.sln -p:Configuration=Release
          mv Release\gotorch.dll Release\gotorch_cpu.dll

      - name: upload
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./lib/Release/gotorch_cpu.dll
          allowUpdates: true
          generateReleaseNotes: true
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          omitBody: true