name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: make
        working-directory: ./lib
        run: |
          wget -O libtorch.zip https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-2.0.1%2Bcpu.zip
          unzip libtorch.zip
          cmake -DCMAKE_PREFIX_PATH=./libtorch -DCMAKE_BUILD_TYPE=Release .
          make

      - name: upload
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./lib/libgotorch.so
          allowUpdates: true
          generateReleaseNotes: true
          token: ${{ secrets.MY_GITHUB_TOKEN }}

  release_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: make
        working-directory: ./lib
        run: |
          wget -O libtorch.zip https://download.pytorch.org/libtorch/cpu/libtorch-macos-2.0.1.zip
          unzip libtorch.zip
          cmake -DCMAKE_PREFIX_PATH=./libtorch -DCMAKE_BUILD_TYPE=Release .
          make

      - name: upload
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./lib/libgotorch.dylib
          allowUpdates: true
          generateReleaseNotes: true
          token: ${{ secrets.MY_GITHUB_TOKEN }}