name: release

on:
  push:
    branches: [ master ]

jobs:
  release_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: cmake
        working-directory: ./lib
        run: |
          curl -L https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-2.0.1%2Bcpu.zip|tar -vx